// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSalon.Data;

namespace WebSalon.Migrations
{
    [DbContext(typeof(WebSalonContext))]
    [Migration("20210601114448_WebSalonMigration")]
    partial class WebSalonMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("WebSalon.Models.Programare", b =>
                {
                    b.Property<int>("ProgramareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("dataOra")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("numeClient")
                        .HasColumnType("longtext");

                    b.Property<string>("telefon")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("username")
                        .HasColumnType("longtext");

                    b.HasKey("ProgramareId");

                    b.ToTable("Programare");
                });

            modelBuilder.Entity("WebSalon.Models.ProgramareServiciu", b =>
                {
                    b.Property<int>("ProgramareId")
                        .HasColumnType("int");

                    b.Property<int>("ServiciuId")
                        .HasColumnType("int");

                    b.HasKey("ProgramareId", "ServiciuId");

                    b.HasIndex("ServiciuId");

                    b.ToTable("ProgramareServiciu");
                });

            modelBuilder.Entity("WebSalon.Models.Serviciu", b =>
                {
                    b.Property<int>("ServiciuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("numeServiciu")
                        .HasColumnType("longtext");

                    b.Property<float>("pret")
                        .HasColumnType("float");

                    b.HasKey("ServiciuId");

                    b.ToTable("Serviciu");
                });

            modelBuilder.Entity("WebSalon.Models.ProgramareServiciu", b =>
                {
                    b.HasOne("WebSalon.Models.Programare", "Programare")
                        .WithMany("ProgramareServiciu")
                        .HasForeignKey("ProgramareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebSalon.Models.Serviciu", "Serviciu")
                        .WithMany("ProgramareServiciu")
                        .HasForeignKey("ServiciuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programare");

                    b.Navigation("Serviciu");
                });

            modelBuilder.Entity("WebSalon.Models.Programare", b =>
                {
                    b.Navigation("ProgramareServiciu");
                });

            modelBuilder.Entity("WebSalon.Models.Serviciu", b =>
                {
                    b.Navigation("ProgramareServiciu");
                });
#pragma warning restore 612, 618
        }
    }
}
