// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSalon.Data;

namespace WebSalon.Migrations
{
    [DbContext(typeof(WebSalonContext))]
    partial class WebSalonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebSalon.Models.Programare", b =>
                {
                    b.Property<int>("ProgramareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dataOra")
                        .HasColumnType("datetime2");

                    b.Property<string>("numeClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgramareId");

                    b.ToTable("Programare");
                });

            modelBuilder.Entity("WebSalon.Models.ProgramareServiciu", b =>
                {
                    b.Property<int>("ProgramareId")
                        .HasColumnType("int");

                    b.Property<int>("ServiciuId")
                        .HasColumnType("int");

                    b.HasKey("ProgramareId", "ServiciuId");

                    b.HasIndex("ServiciuId");

                    b.ToTable("ProgramareServiciu");
                });

            modelBuilder.Entity("WebSalon.Models.Serviciu", b =>
                {
                    b.Property<int>("ServiciuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("numeServiciu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("pret")
                        .HasColumnType("real");

                    b.HasKey("ServiciuId");

                    b.ToTable("Serviciu");
                });

            modelBuilder.Entity("WebSalon.Models.ProgramareServiciu", b =>
                {
                    b.HasOne("WebSalon.Models.Programare", "Programare")
                        .WithMany("ProgramareServiciu")
                        .HasForeignKey("ProgramareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebSalon.Models.Serviciu", "Serviciu")
                        .WithMany("ProgramareServiciu")
                        .HasForeignKey("ServiciuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programare");

                    b.Navigation("Serviciu");
                });

            modelBuilder.Entity("WebSalon.Models.Programare", b =>
                {
                    b.Navigation("ProgramareServiciu");
                });

            modelBuilder.Entity("WebSalon.Models.Serviciu", b =>
                {
                    b.Navigation("ProgramareServiciu");
                });
#pragma warning restore 612, 618
        }
    }
}
